---
title: "Untitled"
output:
  html_document: default
  pdf_document: default
date: "2024-06-17"
---

```{r}

library(ggplot2)

source("Mpox_simulation_N_times.R")

# Run the simulation 1000 times with vaccination effects
set.seed(125)
results_df <- simulate_n_times(1000, vacc_coverage = 0.7, ve_infection = 0.9, ve_death = 0.8, ve_symptoms = 0.7)


summary(results)

# Plot the histogram of QoL reduction
ggplot(results_df, aes(x = overall_qol_reduction)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Histogram of Overall QoL Reduction Due to Mpox",
       x = "Overall QoL Reduction",
       y = "Frequency") +
  theme_minimal()

# Summary of deaths
cat("Summary of total deaths over 1000 simulations:\n")
print(summary(results_df$total_deaths))

# Summary statistics of QoL reduction
cat("Summary of total Qol reduction over 1000 simulations:\n")
print(summary(results_df$overall_qol_reduction))

```
Comparative analysis

```{r}
#Define parameter ranges
coverage_values <- seq(0, 1, by = 0.2)
efficacy_values <- seq(0, 1, by = 0.2)
```
Comparative analysis for vaccination coverage
```{r}
source("Comparative_analysis_function.R")


```